version: '3.8'

services:
  app:
    image: fileapp:latest
    container_name: fileapp
    ports:
      - "8040:9090"
    depends_on:
      - postgres_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/invoice-mvc
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin

  postgres_db:
    image: postgres:latest
    container_name: con
    ports:
      - "5438:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: invoice-mvc
    volumes:
      - D:\postgres_container_data:/var/lib/postgresql/data
