#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}?useSSL=false #jdbc:postgresql://localhost:5433/book-service
#    username: ${DB_USER}   #postgres
#    password: ${DB_PASSWORD} #root
#
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#
#server:
#  port: 8888

spring:
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}?useSSL=false
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: postgresql
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
server:
  port: 8888