version: "3.8"
services:
  springboot_app:
    image: ullash997/spring-app:latest
    container_name: springboot_app_docker
    ports:
      - "8050:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/dockerPractice
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - postgres_db
    networks:
      - app_network

  postgres_db:
    image: postgres:latest
    container_name: postgres_container_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: dockerPractice
    volumes:
      - postgres_data_center_db:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  postgres_data_center_db:

networks:
  app_network:

#version: "3.8"
#services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:9090"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/dockerPractice
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: root
#    depends_on:
#      - postgres_db
#    networks:
#      - app_network
#
#  postgres_db:
#    image: postgres:latest
#    container_name: postgres_db
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: root
#      POSTGRES_DB: dockerPractice
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    networks:
#      - app_network
#
#volumes:
#  postgres_data:
#
#networks:
#  app_network:


#version: '3.8'
#
#services:
#  springboot_app:
#    image: spring-boot-docker:latest
#    container_name: springboot_app_docker
#    ports:
#      - "8050:9090"
#    depends_on:
#      - postgres_db
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/dockerPractice
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: root
#
#  postgres_db:
#    image: postgres:latest
#    container_name: postgres_con
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_USER:
#      POSTGRES_DB: dockerPractice
#    volumes:
#      - G:\pgData:/var/lib/postgresql/data